export const ALL_MATCHS_REQUEST = "ALL_MATCHS_REQUEST";
export const ALL_MATCHS_SUCCESS = "ALL_MATCHS_SUCCESS";
export const ALL_MATCHS_FAIL = "ALL_MATCHS_FAIL";

export const MATCH_DETAILS_REQUEST = "MATCH_DETAILS_REQUEST";
export const MATCH_DETAILS_SUCCESS = "MATCH_DETAILS_SUCCESS";
export const MATCH_DETAILS_FAIL = "MATCH_DETAILS_FAIL";
export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL";
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
// auth actions-types :
// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
// REGISTER :
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// LOAD :
export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";
// LOGOUT :
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// admin actions-types :
export const ADMIN_MATCHS_REQUEST = "ADMIN_MATCHS_REQUEST";
export const ADMIN_MATCHS_SUCCESS = "ADMIN_MATCHS_SUCCESS";
export const ADMIN_MATCHS_FAIL = "ADMIN_MATCHS_FAIL";
// admin delete matchs
export const DELETE_MATCH_REQUEST = "DELETE_MATCH_REQUEST";
export const DELETE_MATCH_SUCCESS = "DELETE_MATCH_SUCCESS";
export const DELETE_MATCH_RESET = "DELETE_MATCH_RESET";
export const DELETE_MATCH_FAIL = "DELETE_MATCH_FAIL";
export const UPDATE_MATCH_REQUEST = "UPDATE_MATCH_REQUEST ";
export const UPDATE_MATCH_SUCCESS = " UPDATE_MATCH_SUCCESS";

export const UPDATE_MATCH_RESET = "UPDATE_MATCH_RESET";
export const UPDATE_MATCH_FAIL = "UPDATE_MATCH_FAIL";
export const NEW_MATCH_REQUEST = "NEW_MATCH_REQUEST";
export const NEW_MATCH_SUCCESS = "NEW_MATCH_SUCCESS";
export const NEW_MATCH_RESET = "NEW_MATCH_RESET";
export const NEW_MATCH_FAIL = "NEW_MATCH_FAIL";
// user actions :
export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";
// update profile :
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
// admin delete user :
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_RESET = "DELETE_USER_RESET";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
// admin update user :
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
// password :
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
// password forgotten :
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const NEW_PASSWORD_REQUEST = "NEW_PASSWORD_REQUEST";
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL";
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
// card actions : 
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const SAVE_CONFIRMING_INFO = "SAVE_CONFIRMING_INFO";
// reservation actions : 
export const CREATE_RESERVATION_REQUEST = "CREATE_RESERVATION_REQUEST";
export const CREATE_RESERVATION_SUCCESS = "CREATE_RESERVATION_SUCCESS";
export const CREATE_RESERVATION_FAIL = "CREATE_RESERVATION_FAIL";

export const MY_RESERVATIONS_REQUEST = "MY_RESERVATIONS_REQUEST";
export const MY_RESERVATIONS_SUCCESS = "MY_RESERVATIONS_SUCCESS";
export const MY_RESERVATIONS_FAIL = "MY_RESERVATIONS_FAIL";

export const ALL_RESERVATIONS_REQUEST = "ALL_RESERVATIONS_REQUEST";
export const ALL_RESERVATIONS_SUCCESS = "ALL_RESERVATIONS_SUCCESS";
export const ALL_RESERVATIONS_FAIL = "ALL_RESERVATIONS_FAIL";

export const UPDATE_RESERVATION_REQUEST = "UPDATE_RESERVATION_REQUEST";
export const UPDATE_RESERVATION_SUCCESS = "UPDATE_RESERVATION_SUCCESS";
export const UPDATE_RESERVATION_RESET = "UPDATE_RESERVATION_RESET";
export const UPDATE_RESERVATION_FAIL = "UPDATE_RESERVATION_FAIL";

export const DELETE_RESERVATION_REQUEST = "DELETE_RESERVATION_REQUEST";
export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS";
export const DELETE_RESERVATION_RESET = "DELETE_RESERVATION_RESET";
export const DELETE_RESERVATION_FAIL = "DELETE_RESERVATION_FAIL";

export const RESERVATION_DETAILS_REQUEST = "RESERVATION_DETAILS_REQUEST";
export const RESERVATION_DETAILS_SUCCESS = "RESERVATION_DETAILS_SUCCESS";
export const RESERVATION_DETAILS_FAIL = "RESERVATION_DETAILS_FAIL";
